---
  - name: Include "{{ansible_os_family}}" ssh recipe
    include: "{{ansible_os_family}}.yaml"

  - name: Include "{{ssh_type_of_node}}" ssh recipe
    include: "{{ssh_type_of_node}}.yaml"

  - name: Modify sudoers file (RedHat)
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '#\s%wheel.*NOPASSWD.*'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    when: ansible_os_family == "RedHat"    
